export default [
  {
    login: "pedrorfmello",
    id: 857574,
    node_id: "MDQ6VXNlcjg1NzU3NA==",
    avatar_url: "https://avatars.githubusercontent.com/u/857574?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/pedrorfmello",
    html_url: "https://github.com/pedrorfmello",
    followers_url: "https://api.github.com/users/pedrorfmello/followers",
    following_url:
      "https://api.github.com/users/pedrorfmello/following{/other_user}",
    gists_url: "https://api.github.com/users/pedrorfmello/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/pedrorfmello/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/pedrorfmello/subscriptions",
    organizations_url: "https://api.github.com/users/pedrorfmello/orgs",
    repos_url: "https://api.github.com/users/pedrorfmello/repos",
    events_url: "https://api.github.com/users/pedrorfmello/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/pedrorfmello/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Gunslinger489",
    id: 12959383,
    node_id: "MDQ6VXNlcjEyOTU5Mzgz",
    avatar_url: "https://avatars.githubusercontent.com/u/12959383?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Gunslinger489",
    html_url: "https://github.com/Gunslinger489",
    followers_url: "https://api.github.com/users/Gunslinger489/followers",
    following_url:
      "https://api.github.com/users/Gunslinger489/following{/other_user}",
    gists_url: "https://api.github.com/users/Gunslinger489/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Gunslinger489/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Gunslinger489/subscriptions",
    organizations_url: "https://api.github.com/users/Gunslinger489/orgs",
    repos_url: "https://api.github.com/users/Gunslinger489/repos",
    events_url: "https://api.github.com/users/Gunslinger489/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Gunslinger489/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "FSantosx",
    id: 16101647,
    node_id: "MDQ6VXNlcjE2MTAxNjQ3",
    avatar_url: "https://avatars.githubusercontent.com/u/16101647?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/FSantosx",
    html_url: "https://github.com/FSantosx",
    followers_url: "https://api.github.com/users/FSantosx/followers",
    following_url:
      "https://api.github.com/users/FSantosx/following{/other_user}",
    gists_url: "https://api.github.com/users/FSantosx/gists{/gist_id}",
    starred_url: "https://api.github.com/users/FSantosx/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/FSantosx/subscriptions",
    organizations_url: "https://api.github.com/users/FSantosx/orgs",
    repos_url: "https://api.github.com/users/FSantosx/repos",
    events_url: "https://api.github.com/users/FSantosx/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/FSantosx/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jcmdsbr",
    id: 33285182,
    node_id: "MDQ6VXNlcjMzMjg1MTgy",
    avatar_url: "https://avatars.githubusercontent.com/u/33285182?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jcmdsbr",
    html_url: "https://github.com/jcmdsbr",
    followers_url: "https://api.github.com/users/jcmdsbr/followers",
    following_url:
      "https://api.github.com/users/jcmdsbr/following{/other_user}",
    gists_url: "https://api.github.com/users/jcmdsbr/gists{/gist_id}",
    starred_url: "https://api.github.com/users/jcmdsbr/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jcmdsbr/subscriptions",
    organizations_url: "https://api.github.com/users/jcmdsbr/orgs",
    repos_url: "https://api.github.com/users/jcmdsbr/repos",
    events_url: "https://api.github.com/users/jcmdsbr/events{/privacy}",
    received_events_url: "https://api.github.com/users/jcmdsbr/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Pacheck",
    id: 35742444,
    node_id: "MDQ6VXNlcjM1NzQyNDQ0",
    avatar_url: "https://avatars.githubusercontent.com/u/35742444?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Pacheck",
    html_url: "https://github.com/Pacheck",
    followers_url: "https://api.github.com/users/Pacheck/followers",
    following_url:
      "https://api.github.com/users/Pacheck/following{/other_user}",
    gists_url: "https://api.github.com/users/Pacheck/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Pacheck/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Pacheck/subscriptions",
    organizations_url: "https://api.github.com/users/Pacheck/orgs",
    repos_url: "https://api.github.com/users/Pacheck/repos",
    events_url: "https://api.github.com/users/Pacheck/events{/privacy}",
    received_events_url: "https://api.github.com/users/Pacheck/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "GersonRocha9",
    id: 38770302,
    node_id: "MDQ6VXNlcjM4NzcwMzAy",
    avatar_url: "https://avatars.githubusercontent.com/u/38770302?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/GersonRocha9",
    html_url: "https://github.com/GersonRocha9",
    followers_url: "https://api.github.com/users/GersonRocha9/followers",
    following_url:
      "https://api.github.com/users/GersonRocha9/following{/other_user}",
    gists_url: "https://api.github.com/users/GersonRocha9/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/GersonRocha9/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/GersonRocha9/subscriptions",
    organizations_url: "https://api.github.com/users/GersonRocha9/orgs",
    repos_url: "https://api.github.com/users/GersonRocha9/repos",
    events_url: "https://api.github.com/users/GersonRocha9/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/GersonRocha9/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "lariandrade",
    id: 44838761,
    node_id: "MDQ6VXNlcjQ0ODM4NzYx",
    avatar_url: "https://avatars.githubusercontent.com/u/44838761?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/lariandrade",
    html_url: "https://github.com/lariandrade",
    followers_url: "https://api.github.com/users/lariandrade/followers",
    following_url:
      "https://api.github.com/users/lariandrade/following{/other_user}",
    gists_url: "https://api.github.com/users/lariandrade/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/lariandrade/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/lariandrade/subscriptions",
    organizations_url: "https://api.github.com/users/lariandrade/orgs",
    repos_url: "https://api.github.com/users/lariandrade/repos",
    events_url: "https://api.github.com/users/lariandrade/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/lariandrade/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jdevstatic",
    id: 47092464,
    node_id: "MDQ6VXNlcjQ3MDkyNDY0",
    avatar_url: "https://avatars.githubusercontent.com/u/47092464?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jdevstatic",
    html_url: "https://github.com/jdevstatic",
    followers_url: "https://api.github.com/users/jdevstatic/followers",
    following_url:
      "https://api.github.com/users/jdevstatic/following{/other_user}",
    gists_url: "https://api.github.com/users/jdevstatic/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/jdevstatic/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jdevstatic/subscriptions",
    organizations_url: "https://api.github.com/users/jdevstatic/orgs",
    repos_url: "https://api.github.com/users/jdevstatic/repos",
    events_url: "https://api.github.com/users/jdevstatic/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jdevstatic/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "GustavoDias7",
    id: 50327760,
    node_id: "MDQ6VXNlcjUwMzI3NzYw",
    avatar_url: "https://avatars.githubusercontent.com/u/50327760?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/GustavoDias7",
    html_url: "https://github.com/GustavoDias7",
    followers_url: "https://api.github.com/users/GustavoDias7/followers",
    following_url:
      "https://api.github.com/users/GustavoDias7/following{/other_user}",
    gists_url: "https://api.github.com/users/GustavoDias7/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/GustavoDias7/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/GustavoDias7/subscriptions",
    organizations_url: "https://api.github.com/users/GustavoDias7/orgs",
    repos_url: "https://api.github.com/users/GustavoDias7/repos",
    events_url: "https://api.github.com/users/GustavoDias7/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/GustavoDias7/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "lucianesantcs",
    id: 52360898,
    node_id: "MDQ6VXNlcjUyMzYwODk4",
    avatar_url: "https://avatars.githubusercontent.com/u/52360898?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/lucianesantcs",
    html_url: "https://github.com/lucianesantcs",
    followers_url: "https://api.github.com/users/lucianesantcs/followers",
    following_url:
      "https://api.github.com/users/lucianesantcs/following{/other_user}",
    gists_url: "https://api.github.com/users/lucianesantcs/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/lucianesantcs/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/lucianesantcs/subscriptions",
    organizations_url: "https://api.github.com/users/lucianesantcs/orgs",
    repos_url: "https://api.github.com/users/lucianesantcs/repos",
    events_url: "https://api.github.com/users/lucianesantcs/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/lucianesantcs/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "marimunari",
    id: 54755896,
    node_id: "MDQ6VXNlcjU0NzU1ODk2",
    avatar_url: "https://avatars.githubusercontent.com/u/54755896?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/marimunari",
    html_url: "https://github.com/marimunari",
    followers_url: "https://api.github.com/users/marimunari/followers",
    following_url:
      "https://api.github.com/users/marimunari/following{/other_user}",
    gists_url: "https://api.github.com/users/marimunari/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/marimunari/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/marimunari/subscriptions",
    organizations_url: "https://api.github.com/users/marimunari/orgs",
    repos_url: "https://api.github.com/users/marimunari/repos",
    events_url: "https://api.github.com/users/marimunari/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/marimunari/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "nicoledbianchin",
    id: 54905149,
    node_id: "MDQ6VXNlcjU0OTA1MTQ5",
    avatar_url: "https://avatars.githubusercontent.com/u/54905149?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nicoledbianchin",
    html_url: "https://github.com/nicoledbianchin",
    followers_url: "https://api.github.com/users/nicoledbianchin/followers",
    following_url:
      "https://api.github.com/users/nicoledbianchin/following{/other_user}",
    gists_url: "https://api.github.com/users/nicoledbianchin/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/nicoledbianchin/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/nicoledbianchin/subscriptions",
    organizations_url: "https://api.github.com/users/nicoledbianchin/orgs",
    repos_url: "https://api.github.com/users/nicoledbianchin/repos",
    events_url: "https://api.github.com/users/nicoledbianchin/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/nicoledbianchin/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "laisps",
    id: 55462189,
    node_id: "MDQ6VXNlcjU1NDYyMTg5",
    avatar_url: "https://avatars.githubusercontent.com/u/55462189?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/laisps",
    html_url: "https://github.com/laisps",
    followers_url: "https://api.github.com/users/laisps/followers",
    following_url: "https://api.github.com/users/laisps/following{/other_user}",
    gists_url: "https://api.github.com/users/laisps/gists{/gist_id}",
    starred_url: "https://api.github.com/users/laisps/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/laisps/subscriptions",
    organizations_url: "https://api.github.com/users/laisps/orgs",
    repos_url: "https://api.github.com/users/laisps/repos",
    events_url: "https://api.github.com/users/laisps/events{/privacy}",
    received_events_url: "https://api.github.com/users/laisps/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "alwspiderc",
    id: 57070379,
    node_id: "MDQ6VXNlcjU3MDcwMzc5",
    avatar_url: "https://avatars.githubusercontent.com/u/57070379?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/alwspiderc",
    html_url: "https://github.com/alwspiderc",
    followers_url: "https://api.github.com/users/alwspiderc/followers",
    following_url:
      "https://api.github.com/users/alwspiderc/following{/other_user}",
    gists_url: "https://api.github.com/users/alwspiderc/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/alwspiderc/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/alwspiderc/subscriptions",
    organizations_url: "https://api.github.com/users/alwspiderc/orgs",
    repos_url: "https://api.github.com/users/alwspiderc/repos",
    events_url: "https://api.github.com/users/alwspiderc/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/alwspiderc/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "annatozaki",
    id: 65266106,
    node_id: "MDQ6VXNlcjY1MjY2MTA2",
    avatar_url: "https://avatars.githubusercontent.com/u/65266106?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/annatozaki",
    html_url: "https://github.com/annatozaki",
    followers_url: "https://api.github.com/users/annatozaki/followers",
    following_url:
      "https://api.github.com/users/annatozaki/following{/other_user}",
    gists_url: "https://api.github.com/users/annatozaki/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/annatozaki/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/annatozaki/subscriptions",
    organizations_url: "https://api.github.com/users/annatozaki/orgs",
    repos_url: "https://api.github.com/users/annatozaki/repos",
    events_url: "https://api.github.com/users/annatozaki/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/annatozaki/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "gabivechiatto",
    id: 70117817,
    node_id: "MDQ6VXNlcjcwMTE3ODE3",
    avatar_url: "https://avatars.githubusercontent.com/u/70117817?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/gabivechiatto",
    html_url: "https://github.com/gabivechiatto",
    followers_url: "https://api.github.com/users/gabivechiatto/followers",
    following_url:
      "https://api.github.com/users/gabivechiatto/following{/other_user}",
    gists_url: "https://api.github.com/users/gabivechiatto/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/gabivechiatto/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/gabivechiatto/subscriptions",
    organizations_url: "https://api.github.com/users/gabivechiatto/orgs",
    repos_url: "https://api.github.com/users/gabivechiatto/repos",
    events_url: "https://api.github.com/users/gabivechiatto/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/gabivechiatto/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "anderama",
    id: 71443197,
    node_id: "MDQ6VXNlcjcxNDQzMTk3",
    avatar_url: "https://avatars.githubusercontent.com/u/71443197?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/anderama",
    html_url: "https://github.com/anderama",
    followers_url: "https://api.github.com/users/anderama/followers",
    following_url:
      "https://api.github.com/users/anderama/following{/other_user}",
    gists_url: "https://api.github.com/users/anderama/gists{/gist_id}",
    starred_url: "https://api.github.com/users/anderama/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/anderama/subscriptions",
    organizations_url: "https://api.github.com/users/anderama/orgs",
    repos_url: "https://api.github.com/users/anderama/repos",
    events_url: "https://api.github.com/users/anderama/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/anderama/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "vinicius-goncalves",
    id: 74028582,
    node_id: "MDQ6VXNlcjc0MDI4NTgy",
    avatar_url: "https://avatars.githubusercontent.com/u/74028582?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/vinicius-goncalves",
    html_url: "https://github.com/vinicius-goncalves",
    followers_url: "https://api.github.com/users/vinicius-goncalves/followers",
    following_url:
      "https://api.github.com/users/vinicius-goncalves/following{/other_user}",
    gists_url:
      "https://api.github.com/users/vinicius-goncalves/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/vinicius-goncalves/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/vinicius-goncalves/subscriptions",
    organizations_url: "https://api.github.com/users/vinicius-goncalves/orgs",
    repos_url: "https://api.github.com/users/vinicius-goncalves/repos",
    events_url:
      "https://api.github.com/users/vinicius-goncalves/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/vinicius-goncalves/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "GuilhermeNied",
    id: 80837854,
    node_id: "MDQ6VXNlcjgwODM3ODU0",
    avatar_url: "https://avatars.githubusercontent.com/u/80837854?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/GuilhermeNied",
    html_url: "https://github.com/GuilhermeNied",
    followers_url: "https://api.github.com/users/GuilhermeNied/followers",
    following_url:
      "https://api.github.com/users/GuilhermeNied/following{/other_user}",
    gists_url: "https://api.github.com/users/GuilhermeNied/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/GuilhermeNied/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/GuilhermeNied/subscriptions",
    organizations_url: "https://api.github.com/users/GuilhermeNied/orgs",
    repos_url: "https://api.github.com/users/GuilhermeNied/repos",
    events_url: "https://api.github.com/users/GuilhermeNied/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/GuilhermeNied/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "RafaelPrincival",
    id: 82247772,
    node_id: "MDQ6VXNlcjgyMjQ3Nzcy",
    avatar_url: "https://avatars.githubusercontent.com/u/82247772?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/RafaelPrincival",
    html_url: "https://github.com/RafaelPrincival",
    followers_url: "https://api.github.com/users/RafaelPrincival/followers",
    following_url:
      "https://api.github.com/users/RafaelPrincival/following{/other_user}",
    gists_url: "https://api.github.com/users/RafaelPrincival/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/RafaelPrincival/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/RafaelPrincival/subscriptions",
    organizations_url: "https://api.github.com/users/RafaelPrincival/orgs",
    repos_url: "https://api.github.com/users/RafaelPrincival/repos",
    events_url: "https://api.github.com/users/RafaelPrincival/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/RafaelPrincival/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "g-zato",
    id: 84541955,
    node_id: "MDQ6VXNlcjg0NTQxOTU1",
    avatar_url: "https://avatars.githubusercontent.com/u/84541955?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/g-zato",
    html_url: "https://github.com/g-zato",
    followers_url: "https://api.github.com/users/g-zato/followers",
    following_url: "https://api.github.com/users/g-zato/following{/other_user}",
    gists_url: "https://api.github.com/users/g-zato/gists{/gist_id}",
    starred_url: "https://api.github.com/users/g-zato/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/g-zato/subscriptions",
    organizations_url: "https://api.github.com/users/g-zato/orgs",
    repos_url: "https://api.github.com/users/g-zato/repos",
    events_url: "https://api.github.com/users/g-zato/events{/privacy}",
    received_events_url: "https://api.github.com/users/g-zato/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "saravbarbosa",
    id: 97530586,
    node_id: "U_kgDOBdAy2g",
    avatar_url: "https://avatars.githubusercontent.com/u/97530586?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/saravbarbosa",
    html_url: "https://github.com/saravbarbosa",
    followers_url: "https://api.github.com/users/saravbarbosa/followers",
    following_url:
      "https://api.github.com/users/saravbarbosa/following{/other_user}",
    gists_url: "https://api.github.com/users/saravbarbosa/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/saravbarbosa/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/saravbarbosa/subscriptions",
    organizations_url: "https://api.github.com/users/saravbarbosa/orgs",
    repos_url: "https://api.github.com/users/saravbarbosa/repos",
    events_url: "https://api.github.com/users/saravbarbosa/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/saravbarbosa/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "GuiMM91",
    id: 101063645,
    node_id: "U_kgDOBgYb3Q",
    avatar_url: "https://avatars.githubusercontent.com/u/101063645?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/GuiMM91",
    html_url: "https://github.com/GuiMM91",
    followers_url: "https://api.github.com/users/GuiMM91/followers",
    following_url:
      "https://api.github.com/users/GuiMM91/following{/other_user}",
    gists_url: "https://api.github.com/users/GuiMM91/gists{/gist_id}",
    starred_url: "https://api.github.com/users/GuiMM91/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/GuiMM91/subscriptions",
    organizations_url: "https://api.github.com/users/GuiMM91/orgs",
    repos_url: "https://api.github.com/users/GuiMM91/repos",
    events_url: "https://api.github.com/users/GuiMM91/events{/privacy}",
    received_events_url: "https://api.github.com/users/GuiMM91/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "gabrielssconceicao",
    id: 101210140,
    node_id: "U_kgDOBghYHA",
    avatar_url: "https://avatars.githubusercontent.com/u/101210140?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/gabrielssconceicao",
    html_url: "https://github.com/gabrielssconceicao",
    followers_url: "https://api.github.com/users/gabrielssconceicao/followers",
    following_url:
      "https://api.github.com/users/gabrielssconceicao/following{/other_user}",
    gists_url:
      "https://api.github.com/users/gabrielssconceicao/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/gabrielssconceicao/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/gabrielssconceicao/subscriptions",
    organizations_url: "https://api.github.com/users/gabrielssconceicao/orgs",
    repos_url: "https://api.github.com/users/gabrielssconceicao/repos",
    events_url:
      "https://api.github.com/users/gabrielssconceicao/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/gabrielssconceicao/received_events",
    type: "User",
    site_admin: false,
  },
];
