export default {
  login: "lhenriquedev",
  id: 72282029,
  node_id: "MDQ6VXNlcjcyMjgyMDI5",
  avatar_url: "https://avatars.githubusercontent.com/u/72282029?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/lhenriquedev",
  html_url: "https://github.com/lhenriquedev",
  followers_url: "https://api.github.com/users/lhenriquedev/followers",
  following_url:
    "https://api.github.com/users/lhenriquedev/following{/other_user}",
  gists_url: "https://api.github.com/users/lhenriquedev/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/lhenriquedev/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/lhenriquedev/subscriptions",
  organizations_url: "https://api.github.com/users/lhenriquedev/orgs",
  repos_url: "https://api.github.com/users/lhenriquedev/repos",
  events_url: "https://api.github.com/users/lhenriquedev/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/lhenriquedev/received_events",
  type: "User",
  site_admin: false,
  name: "Henrique Marques",
  company: "@isket",
  blog: "",
  location: "Porto Alegre, RS",
  email: null,
  hireable: true,
  bio: "Frontend Developer. 🇧🇷 🔥 ☕  ",
  twitter_username: "lhenrique_dev",
  public_repos: 93,
  public_gists: 3,
  followers: 24,
  following: 93,
  created_at: "2020-10-02T21:36:21Z",
  updated_at: "2023-01-20T00:10:12Z",
};
